const DPI=300;
const paperSizes={"3R":[3.5,5],"4R":[4,6],"5R":[5,7],"A4":[8.27,11.69],"Letter":[8.5,11],"Legal":[8.5,14]};
const presets={"1x1":[1,1,8],"1.5x1.5":[1.5,1.5,6],"2x2":[2,2,4],passport:[1.37,1.77,6],visa:[2,2,4],halfbody:[3,4,2],wallet:[2.5,3.5,2]};
const polaroids={mini:{name:'Instax Mini',film:[54,86],image:[46,62],top:4},square:{name:'Instax Square',film:[72,86],image:[62,62],top:5},wide:{name:'Instax Wide',film:[108,86],image:[99,62],top:4}};
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const state={images:[],active:0,sizes:[{w:2,h:2,unit:'inch',qty:4}],paper:'4R',landscape:false,guides:true,labels:true,border:true,margin:.15,spacing:.06,zoom:1,rot:0,flip:false,brightness:100,contrast:100,polaroid:false,pMargin:.18,pSpacing:.08,pBorder:.14,pLandscape:false,pGuides:true,pLabels:true,pFormat:'mini'};
let cropper=null,previewZoom=1,currentCropMode='id';
const canvas=$('#previewCanvas'), ctx=canvas.getContext('2d');

function inch(v,u){v=+v||0; return u==='mm'?v/25.4:u==='cm'?v/2.54:v;}
function paper(){let [w,h]=paperSizes[state.paper]; const land=state.polaroid?state.pLandscape:state.landscape; return land?[Math.max(w,h),Math.min(w,h)]:[Math.min(w,h),Math.max(w,h)];}
function fitPreview(){const wrap=$('.canvas-wrap');if(!wrap)return;const [pw,ph]=paper();const styles=getComputedStyle(wrap);const padX=parseFloat(styles.paddingLeft)+parseFloat(styles.paddingRight);const padY=parseFloat(styles.paddingTop)+parseFloat(styles.paddingBottom);const maxW=Math.max(120,wrap.clientWidth-padX);const maxH=Math.max(160,wrap.clientHeight-padY);const ratio=pw/ph;let displayW=maxW,displayH=displayW/ratio;if(displayH>maxH){displayH=maxH;displayW=displayH*ratio;}displayW*=previewZoom;displayH*=previewZoom;canvas.style.width=`${Math.floor(displayW)}px`;canvas.style.height=`${Math.floor(displayH)}px`;}
function loadFile(file){return new Promise(res=>{const r=new FileReader(); r.onload=()=>{const img=new Image(); img.onload=()=>res({name:file.name,src:r.result,img}); img.src=r.result}; r.readAsDataURL(file);});}
async function addFiles(files,polaroid=false){const valid=[...files].filter(f=>/image\/(jpeg|png)/.test(f.type)); const imgs=await Promise.all(valid.map(loadFile)); const firstNew=state.images.length; state.images.push(...imgs); if(polaroid)state.polaroid=true;if(imgs.length){state.active=firstNew;setupCrop(state.images[state.active].src,polaroid?'polaroid':'id');}renderThumbs();render();}
function setupCrop(src,mode='id'){currentCropMode=mode;const isPolaroid=mode==='polaroid',card=$(isPolaroid?'#polaroidCropCard':'#cropCard'),other=$(isPolaroid?'#cropCard':'#polaroidCropCard'),imageEl=$(isPolaroid?'#polaroidCropImage':'#cropImage'),applyBtn=$(isPolaroid?'#applyPolaroidCrop':'#applyCrop');other.classList.add('hidden');card.classList.remove('hidden');imageEl.src=src;if(isPolaroid)$('#cropPhotoNumber').textContent=`Photo ${state.active+1} of ${state.images.length}`;if(cropper){cropper.destroy();cropper=null;}if(typeof Cropper==='undefined'){applyBtn.disabled=true;applyBtn.textContent='Cropper unavailable';return;}applyBtn.disabled=false;applyBtn.textContent='Apply crop';const spec=polaroids[state.pFormat];cropper=new Cropper(imageEl,{viewMode:1,dragMode:'move',autoCropArea:.86,background:false,responsive:true,movable:true,zoomable:true,cropBoxMovable:true,cropBoxResizable:true,toggleDragModeOnDblclick:false,aspectRatio:isPolaroid?spec.image[0]/spec.image[1]:NaN});}
function renderThumbs(){['#thumbList','#polaroidThumbList'].forEach(selector=>{const box=$(selector),mode=selector==='#polaroidThumbList'?'polaroid':'id';box.innerHTML='';state.images.forEach((im,i)=>{const d=document.createElement('div');d.className=`thumb${i===state.active?' active':''}`;d.innerHTML=`<img src="${im.src}" alt="${im.name}"><span>${i+1}. ${im.name.slice(0,10)}</span>`;d.onclick=()=>{state.active=i;renderThumbs();setupCrop(im.src,mode);};box.appendChild(d);});});}
function drawProcessed(img,x,y,w,h,cover=true){ctx.save(); ctx.beginPath(); ctx.rect(x,y,w,h); ctx.clip(); ctx.filter=`brightness(${state.brightness}%) contrast(${state.contrast}%)`; ctx.translate(x+w/2,y+h/2); ctx.rotate(state.rot*Math.PI/180); ctx.scale(state.flip?-state.zoom:state.zoom,state.zoom); const iw=img.width, ih=img.height, sc=cover?Math.max(w/iw,h/ih):Math.min(w/iw,h/ih); ctx.drawImage(img,-iw*sc/2,-ih*sc/2,iw*sc,ih*sc); ctx.restore(); ctx.filter='none';}
function drawGuides(x,y,w,h){ctx.save(); ctx.strokeStyle='#67a9e8'; ctx.setLineDash([10,8]); ctx.lineWidth=2; ctx.strokeRect(x,y,w,h); ctx.restore();}
function drawBorder(x,y,w,h){ctx.save();ctx.strokeStyle='#1f2937';ctx.setLineDash([]);ctx.lineWidth=2;ctx.strokeRect(x,y,w,h);ctx.restore();}
function layoutItems(items,W,H,margin,spacing){let x=margin,y=margin,rowH=0,rows=[],row=[]; const out=[]; items.forEach(it=>{if(x+it.w>W-margin+.1 && row.length){const used=x-spacing-margin; const off=(W-2*margin-used)/2; row.forEach(o=>o.x+=off); rows.push(row); row=[]; x=margin; y+=rowH+spacing; rowH=0;} if(y+it.h<=H-margin+.1){const o={...it,x,y}; out.push(o); row.push(o); x+=it.w+spacing; rowH=Math.max(rowH,it.h);}}); if(row.length){const used=x-spacing-margin; const off=(W-2*margin-used)/2; row.forEach(o=>o.x+=off);} return out;}
function render(){const [pw,ph]=paper(); canvas.width=Math.round(pw*DPI); canvas.height=Math.round(ph*DPI); canvas.style.aspectRatio=`${pw}/${ph}`; ctx.fillStyle='#fff'; ctx.fillRect(0,0,canvas.width,canvas.height); ctx.fillStyle='#f7fbff'; ctx.fillRect(0,0,canvas.width,canvas.height); const margin=(state.polaroid?state.pMargin:state.margin)*DPI, spacing=(state.polaroid?state.pSpacing:state.spacing)*DPI; let count=0, pages=1;
 if(!state.images.length){ctx.fillStyle='#dbeafe'; ctx.fillRect(margin,margin,canvas.width-2*margin,canvas.height-2*margin); ctx.fillStyle='#2783de'; ctx.font='600 42px system-ui'; ctx.textAlign='center'; ctx.fillText('Upload JPG or PNG photos',canvas.width/2,canvas.height/2); updateStats(0,1,pw,ph); requestAnimationFrame(fitPreview); return;}
 if(state.polaroid){const spec=polaroids[state.pFormat],mm=v=>v/25.4*DPI; const items=state.images.map((im,i)=>({img:im.img,label:im.name,w:mm(spec.film[0]),h:mm(spec.film[1]),i})); const placed=layoutItems(items,canvas.width,canvas.height,margin,spacing); pages=Math.max(1,Math.ceil(items.length/Math.max(1,placed.length))); count=items.length; placed.forEach(p=>{ctx.fillStyle='#fff';ctx.shadowColor='rgba(0,0,0,.12)';ctx.shadowBlur=8;ctx.shadowOffsetY=3;ctx.fillRect(p.x,p.y,p.w,p.h);ctx.shadowColor='transparent';const imageW=mm(spec.image[0]),imageH=mm(spec.image[1]),imageX=p.x+(p.w-imageW)/2,imageY=p.y+mm(spec.top);drawProcessed(p.img,imageX,imageY,imageW,imageH,true);ctx.save();ctx.strokeStyle='rgba(31,41,55,.28)';ctx.lineWidth=Math.max(1,state.pBorder*DPI*.04);ctx.strokeRect(imageX,imageY,imageW,imageH);ctx.restore();if(state.pGuides)drawGuides(p.x,p.y,p.w,p.h);if(state.pLabels){ctx.fillStyle='#1f2937';ctx.font='22px system-ui';ctx.textAlign='center';ctx.fillText(spec.name,p.x+p.w/2,p.y+p.h-mm(4));}});
 } else {const items=[]; state.sizes.forEach(s=>{for(let i=0;i<s.qty;i++)items.push({img:state.images[state.active]?.img||state.images[0].img,label:`${s.w}×${s.h} ${s.unit}`,w:inch(s.w,s.unit)*DPI,h:inch(s.h,s.unit)*DPI});}); const placed=layoutItems(items,canvas.width,canvas.height,margin,spacing); pages=Math.max(1,Math.ceil(items.length/Math.max(1,placed.length))); count=items.length; placed.forEach(p=>{drawProcessed(p.img,p.x,p.y,p.w,p.h,true); if(state.border)drawBorder(p.x,p.y,p.w,p.h); if(state.guides)drawGuides(p.x,p.y,p.w,p.h); if(state.labels){ctx.fillStyle='rgba(255,255,255,.9)';ctx.fillRect(p.x,p.y+p.h-34,p.w,34);ctx.fillStyle='#111827';ctx.font='22px system-ui';ctx.textAlign='center';ctx.fillText(p.label,p.x+p.w/2,p.y+p.h-10);}});}
 updateStats(count,pages,pw,ph); requestAnimationFrame(fitPreview);
}
function updateStats(count,pages,w,h){$('#pageCount').textContent=`${pages} page${pages>1?'s':''}`; $('#photoCount').textContent=`${count} photos`; $('#paperLabel').textContent=`${state.paper} ${w>h?'landscape':'portrait'}`;}
function refreshSizes(){const box=$('#sizesList'); box.innerHTML=''; state.sizes.forEach((s,i)=>{const d=document.createElement('div');d.className='size-item';d.innerHTML=`<b>${s.w} × ${s.h} ${s.unit}</b><span>${s.qty} copies</span><button class="remove">Remove</button>`; d.querySelector('button').onclick=()=>{state.sizes.splice(i,1);refreshSizes();render()}; box.appendChild(d);});}
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab,.panel:not(.always)').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active');state.polaroid=b.dataset.tab==='polaroid';render();});
['dragenter','dragover'].forEach(e=>$('#dropZone').addEventListener(e,ev=>{ev.preventDefault();$('#dropZone').classList.add('drag')})); ['dragleave','drop'].forEach(e=>$('#dropZone').addEventListener(e,ev=>{$('#dropZone').classList.remove('drag')})); $('#dropZone').ondrop=e=>{e.preventDefault();addFiles(e.dataTransfer.files)}; $('#photoInput').onchange=e=>addFiles(e.target.files); $('#multiInput').onchange=e=>addFiles(e.target.files,true);
['dragenter','dragover'].forEach(type=>$('#polaroidDropZone').addEventListener(type,e=>{e.preventDefault();$('#polaroidDropZone').classList.add('drag')}));
['dragleave','drop'].forEach(type=>$('#polaroidDropZone').addEventListener(type,e=>{$('#polaroidDropZone').classList.remove('drag')}));
$('#polaroidDropZone').ondrop=e=>{e.preventDefault();addFiles(e.dataTransfer.files,true)};
$('#clearPhotos').onclick=()=>{state.images=[];state.active=0;$('#photoInput').value='';$('#multiInput').value='';if(cropper){cropper.destroy();cropper=null;}$('#cropCard').classList.add('hidden');$('#polaroidCropCard').classList.add('hidden');renderThumbs();render();};
function applyCurrentCrop(){if(!cropper||!state.images[state.active])return;const data=cropper.getCroppedCanvas({imageSmoothingEnabled:true,imageSmoothingQuality:'high',width:1200}).toDataURL('image/png');const img=new Image();img.onload=()=>{state.images[state.active]={...state.images[state.active],src:data,img};renderThumbs();setupCrop(data,currentCropMode);render();};img.src=data;}
$('#applyCrop').onclick=applyCurrentCrop;$('#applyPolaroidCrop').onclick=applyCurrentCrop;$('#resetCrop').onclick=()=>cropper&&cropper.reset();$('#resetPolaroidCrop').onclick=()=>cropper&&cropper.reset();
$('#presetSelect').onchange=e=>{const p=presets[e.target.value]; $('#widthInput').value=p[0]; $('#heightInput').value=p[1]; $('#qtyInput').value=p[2]; state.sizes=[{w:p[0],h:p[1],unit:'inch',qty:p[2]}]; refreshSizes(); render();};
$('#addSize').onclick=()=>{state.sizes.push({w:+$('#widthInput').value,h:+$('#heightInput').value,unit:$('#unitInput').value,qty:+$('#qtyInput').value});refreshSizes();render();};
$('#paperButtons').onclick=e=>{if(e.target.dataset.paper){state.paper=e.target.dataset.paper; $$('#paperButtons button').forEach(b=>b.classList.toggle('active',b===e.target)); render();}};
[['marginSlider','margin','marginOut',' in'],['spacingSlider','spacing','spacingOut',' in'],['pMargin','pMargin','pMarginOut',' in'],['pSpacing','pSpacing','pSpacingOut',' in'],['borderSlider','pBorder','borderOut',' in'],['zoom','zoom','zoomOut','x'],['brightness','brightness','brightnessOut','%'],['contrast','contrast','contrastOut','%']].forEach(([id,key,out,suf])=>{$('#'+id).oninput=e=>{state[key]=+e.target.value; $('#'+out).textContent=(key==='zoom'?state[key].toFixed(2):state[key])+suf; render();};});
[['landscape','landscape'],['guides','guides'],['labels','labels'],['showBorder','border'],['pLandscape','pLandscape'],['pGuides','pGuides'],['pLabels','pLabels']].forEach(([id,key])=>$('#'+id).onchange=e=>{state[key]=e.target.checked;render();});
function updatePolaroidSpec(){const spec=polaroids[state.pFormat];$('#polaroidSpec').innerHTML=`<strong>${spec.name}</strong><span>Film ${spec.film[0]} × ${spec.film[1]} mm</span><span>Image ${spec.image[0]} × ${spec.image[1]} mm</span>`;}
$('#polaroidFormat').onchange=e=>{state.pFormat=e.target.value;updatePolaroidSpec();if(currentCropMode==='polaroid'&&state.images[state.active])setupCrop(state.images[state.active].src,'polaroid');render();}; $('#rotateBtn').onclick=()=>{state.rot=(state.rot+90)%360;render();}; $('#flipBtn').onclick=()=>{state.flip=!state.flip;render();};
function setPreviewZoom(value){previewZoom=Math.min(2.5,Math.max(.5,value));$('#previewZoomReset').textContent=`${Math.round(previewZoom*100)}%`;fitPreview();}
$('#previewZoomOut').onclick=()=>setPreviewZoom(previewZoom-.25);
$('#previewZoomIn').onclick=()=>setPreviewZoom(previewZoom+.25);
$('#previewZoomReset').onclick=()=>setPreviewZoom(1);
$('#downloadPng').onclick=()=>{const a=document.createElement('a');a.download='easy-photo-studio-layout-300dpi.png';a.href=canvas.toDataURL('image/png');a.click();};
$('#printBtn').onclick=()=>{const [w,h]=paper(); const win=window.open('','_blank'); if(!win)return alert('Please allow pop-ups to print.'); win.document.write(`<!doctype html><html><head><title>EASY PHOTO STUDIO — Print Layout</title><style>@page{size:${w}in ${h}in;margin:0}html,body{margin:0}img{display:block;width:${w}in;height:${h}in}</style></head><body><img src="${canvas.toDataURL('image/png')}"><script>onload=()=>setTimeout(()=>{print();close()},250)<\/script></body></html>`); win.document.close();};
$('#downloadPdf').onclick=()=>{if(!window.jspdf){alert('PDF library could not load. Use Print and choose “Save as PDF”.');return;} const {jsPDF}=window.jspdf; const [w,h]=paper(); const pdf=new jsPDF({orientation:w>h?'landscape':'portrait',unit:'in',format:[w,h]}); pdf.addImage(canvas.toDataURL('image/png'),'PNG',0,0,w,h); pdf.save('easy-photo-studio-layout.pdf');};

const FEEDBACK_KEY='id-photo-generator-feedback-v1';
function getFeedback(){try{const saved=JSON.parse(localStorage.getItem(FEEDBACK_KEY)||'[]');return Array.isArray(saved)?saved:[];}catch{return [];}}
function renderFeedback(){const list=$('#feedbackList'),items=getFeedback();list.innerHTML='';if(!items.length){const empty=document.createElement('div');empty.className='feedback-empty';empty.textContent='No feedback saved yet.';list.appendChild(empty);return;}items.slice().reverse().forEach(item=>{const entry=document.createElement('article');entry.className='feedback-entry';const head=document.createElement('div');head.className='feedback-entry-head';const name=document.createElement('strong');name.textContent=item.name;const time=document.createElement('time');time.dateTime=item.createdAt;time.textContent=new Date(item.createdAt).toLocaleString();const comment=document.createElement('p');comment.textContent=item.comment;head.append(name,time);entry.append(head,comment);list.appendChild(entry);});}
$('#feedbackBtn').onclick=()=>{renderFeedback();$('#feedbackStatus').textContent='';const dialog=$('#feedbackDialog');if(typeof dialog.showModal==='function')dialog.showModal();else dialog.setAttribute('open','');};
$('#closeFeedback').onclick=()=>$('#feedbackDialog').close();
$('#feedbackForm').onsubmit=e=>{e.preventDefault();const name=$('#feedbackName').value.trim(),comment=$('#feedbackComment').value.trim(),status=$('#feedbackStatus');status.style.color='#c2413b';if(!name||!comment){status.textContent='Enter your name and a comment.';return;}const items=getFeedback();let consecutive=0;for(let i=items.length-1;i>=0;i--){if(items[i].name.trim().toLowerCase()===name.toLowerCase())consecutive++;else break;}if(consecutive>=2){status.textContent='This user already posted 2 consecutive comments. Another user must comment before they can post again.';return;}items.push({id:`${Date.now()}-${Math.random().toString(16).slice(2)}`,name,comment,createdAt:new Date().toISOString()});try{localStorage.setItem(FEEDBACK_KEY,JSON.stringify(items));$('#feedbackComment').value='';status.style.color='#287a52';status.textContent='Feedback saved in this browser.';renderFeedback();}catch{status.textContent='Feedback could not be saved. Check browser storage permissions.';}};

refreshSizes(); render();
const previewObserver=new ResizeObserver(fitPreview);previewObserver.observe($('.canvas-wrap'));window.addEventListener('resize',fitPreview);